
ARMADILLO_VERSION=7.500.2
ARMADILLO_HOME=/opt/armadillo/${ARMADILLO_VERSION}
ARMADILLO_INCLUDE=${ARMADILLO_HOME}/include
ARMADILLO_LIB=${ARMADILLO_HOME}/lib

WITH_ARMADILLO_UTIL = true
TEST_AGAINST_ARMADILLO = true
